### PR TITLE
Implement ARRAY_AGG(DISTINCT ...)

### PR DESCRIPTION
**Pull request by james727**
# Which issue does this PR close?
Closes https://github.com/apache/arrow-datafusion/issues/1323

# What changes are included in this PR?
This includes the implementation of `array_agg(distinct ...)`. I also moved `phsyical_plan/distinct_expression.rs` into `physical_plan/expression` - I wanted to reuse a private test utility in `physical_plan/expression`, and it seemed like a more natural location for it anyways. I can move it back if preferred though.

# Are there any user-facing changes?
This adds net-new functionality. Not sure if any doc updates are needed though.

# Input needed
I'm interested in any tips on improving the testing approach. It's pretty annoying that the output order is non-deterministic here, and the lack of `ORD` implementation for `ScalarValue` makes a sort + equality check approach difficult as well. I'm new to Rust though so I'm sure there are better ways to structure this than what I've done so far.

### CODE REVIEW

File: datafusion/src/physical_plan/aggregates.rs [hunk 1]
```diff
@@ -454,42 +452,40 @@ mod tests {
...
-                        assert!(result_agg_phy_exprs_distinct
-                            .as_any()
-                            .is::<DistinctCount>());
-                        assert_eq!("c1", result_agg_phy_exprs_distinct.name());
+                        assert!(result_distinct.as_any().is::<DistinctCount>());
+                        assert_eq!("c1", result_distinct.name());
                         assert_eq!(
                             Field::new("c1", DataType::UInt64, true),
-                            result_agg_phy_exprs_distinct.field().unwrap()
+                            result_distinct.field().unwrap()
```
Comment (alamb) [inline datafusion/src/physical_plan/aggregates.rs:462]: well that is certainly much nicer to read 👍

File: datafusion/src/physical_plan/expressions/distinct_expressions.rs [hunk 2]
```diff
@@ -207,17 +208,155 @@ impl Accumulator for DistinctCountAccumulator {
...
+
+impl Accumulator for DistinctArrayAggAccumulator {
+    fn state(&self) -> Result<Vec<ScalarValue>> {
+        Ok(vec![ScalarValue::List(
+            Some(Box::new(self.values.clone().into_iter().collect())),
+            Box::new(self.datatype.clone()),
+        )])
+    }
+
+    fn update(&mut self, _values: &[ScalarValue]) -> Result<()> {
```
Comment (alamb) [inline datafusion/src/physical_plan/expressions/distinct_expressions.rs:306]: I think this will need to be removed now that https://github.com/apache/arrow-datafusion/pull/1582 is merged

File: datafusion/src/physical_plan/expressions/distinct_expressions.rs [hunk 3]
```diff
@@ -207,17 +208,155 @@ impl Accumulator for DistinctCountAccumulator {
...
+        assert_eq!(values.len(), 1, "batch input should only include 1 column!");
+
+        let arr = &values[0];
+        for i in 0..arr.len() {
+            self.values.insert(ScalarValue::try_from_array(arr, i)?);
+        }
+        Ok(())
+    }
+
+    fn merge(&mut self, _states: &[ScalarValue]) -> Result<()> {
```
Comment (alamb) [inline datafusion/src/physical_plan/expressions/distinct_expressions.rs:320]: likewise this

File: datafusion/src/physical_plan/expressions/distinct_expressions.rs [hunk 4]
```diff
@@ -705,4 +844,151 @@ mod tests {
...
+                assert_eq!(e.len(), a.len());
+
+                let h1: HashSet<ScalarValue> = HashSet::from_iter(e.clone().into_iter());
+                let h2: HashSet<ScalarValue> = HashSet::from_iter(a.into_iter());
+
+                // Check that e's elements are unique.
+                assert_eq!(h1.len(), e.len());
+
+                // Check that a contains the same unique elements as e.
+                assert_eq!(h1, h2);
```
Comment (alamb) [inline datafusion/src/physical_plan/expressions/distinct_expressions.rs:881]: ScalarValue does implement `PartialOrd`-- the reason it doesn't implement Ord is that it doesn't really make sense to compare different variant types -- e.g. `ScalarValue::List` and `ScalarValue::Boolean`

However, in your test cases you are always comparing the same enum, so you can do something like the following (which will panic if there is a problem comparing the `ScalarValue`s in the test):


```suggestion
                // workaround lack of Ord of ScalarValue
                let cmp = |a: &ScalarValue, b: &ScalarValue| {
                    a.partial_cmp(b).expect("Can compare ScalarValues")
                };
                e.as_mut().sort_by(cmp);
                a.as_mut().sort_by(cmp);

                // Check that the inputs are the same
                assert_eq!(e, a);
```

File: datafusion/tests/sql/aggregates.rs [hunk 5]
```diff
@@ -410,3 +411,58 @@ async fn csv_query_array_agg_one() -> Result<()> {
...
+    );
+
+    // We should have 1 row containing a list
+    let column = actual[0].column(0);
+    assert_eq!(column.len(), 1);
+
+    let list = ScalarValue::try_from_array(column, 0)?;
+    let mut contents = vec![];
+    match list {
+        // Since ScalarValue does not implement ORD, we must extract the underlying values
```
Comment (alamb) [inline datafusion/tests/sql/aggregates.rs:445]: 👍

**Review by alamb — APPROVED** [review]
@james727  I am sorry for the delayed review. There has been a lot going on in arrow and datafusion recently!

The code looks (very) good to me; However, there will be a logical conflict when it is merged with the latest master (need to remove `update` and `merge`). Can you please do so and I'll get this PR merged?

I also left a suggestion about how you can work around the lack of `Ord` in `ScalarValue`

File: datafusion/src/physical_plan/expressions/distinct_expressions.rs (hunk 4 above)
Comment (james727) [reply datafusion/src/physical_plan/expressions/distinct_expressions.rs:881]: Thank you! This is much nicer - I noticed the `PartialOrd` implementation but was unsure of how to actually use it.

**Comment by alamb** [comment]
There are a few conflicts in this PR that need to be cleaned up before it can be merged.

**Comment by james727** [comment]
No worries @alamb - I've noticed a ton of activity and figured this is a relatively low-priority change. Appreciate the review. I've rebased to fix conflicts and cleaned up the tests with your suggestion, so this is ready for another look whenever you have time.

Re: conflicts - yep, sorry for the confusion. I noticed your review last night and responded to a couple of things but didn't have time to update the PR.

**Comment by alamb** [comment]
Thanks @james727 !
