### ISSUE TITLE
Should update rust to 1.72

### ISSUE THREAD

**Issue by Ted-Jiang** [apache/arrow-datafusion#8743]
### Is your feature request related to a problem or challenge?

Try to build df got 
```
error[E0658]: use of unstable library feature 'stdsimd'
   --> /Users/yangjiang/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ahash-0.8.7/src/operations.rs:124:24
    |
124 |     let res = unsafe { vaesmcq_u8(vaeseq_u8(transmute!(value), transmute!(0u128))) };
    |                        ^^^^^^^^^^
    |
    = note: see issue #48556 <https://github.com/rust-lang/rust/issues/48556> for more information
    = help: add `#![feature(stdsimd)]` to the crate attributes to enable

```

### Describe the solution you'd like

From the ticket 
https://github.com/tkaitchuck/aHash/issues/195
we should update rust to 1.72

**Comment by Ted-Jiang** [comment]
@alamb  could you give me some advice? any concern? 😄

**Comment by alamb** [comment]
In theory we have a check for min rust version contributed in https://github.com/apache/arrow-datafusion/pull/7123 from @sarutak 


https://github.com/apache/arrow-datafusion/blob/819d3577872a082f2aea7a68ae83d68534049662/datafusion/core/Cargo.toml#L30

However, it appears not to be working if you can't compile using `1.71`

Maybe we can figure out why the CI check isn't failing and then upgrade to rust 1.72 as a MSRV

**Comment by Dandandan** [comment]
This is caused by a newer version of ahash, see https://github.com/tkaitchuck/aHash/issues/195

**Comment by Jefffrey** [comment]
> Maybe we can figure out why the CI check isn't failing and then upgrade to rust 1.72 as a MSRV

CI check not failing because ahash didn't bump their own MSRV. I've raised a PR for them now: https://github.com/tkaitchuck/aHash/pull/196

**Comment by Jefffrey** [comment]
Also, worth fixing as well places which don't use the workspace rust-version, e.g.

https://github.com/apache/arrow-datafusion/blob/e5036d0e760b637724e8ac59c32924f126311d39/docs/Cargo.toml#L18-L29

https://github.com/apache/arrow-datafusion/blob/e5036d0e760b637724e8ac59c32924f126311d39/benchmarks/Cargo.toml#L18-L27

https://github.com/apache/arrow-datafusion/blob/e5036d0e760b637724e8ac59c32924f126311d39/datafusion/core/Cargo.toml#L18-L30

https://github.com/apache/arrow-datafusion/blob/e5036d0e760b637724e8ac59c32924f126311d39/datafusion/proto/Cargo.toml#L18-L29

https://github.com/apache/arrow-datafusion/blob/e5036d0e760b637724e8ac59c32924f126311d39/datafusion/wasmtest/Cargo.toml#L18-L28

https://github.com/apache/arrow-datafusion/blob/e5036d0e760b637724e8ac59c32924f126311d39/datafusion/substrait/Cargo.toml#L18-L28

Or if theres a reason these should differ from what's specified in `Cargo.toml` then leave comments explaining this.

Should ideally only have one place to specify:

https://github.com/apache/arrow-datafusion/blob/e5036d0e760b637724e8ac59c32924f126311d39/Cargo.toml#L24-L32
