### PR TITLE
Fix build on main due to logical conflict

### PR DESCRIPTION
**Pull request by alamb**
# Which issue does this PR close?

N/A

# Rationale for this change

https://github.com/apache/arrow-datafusion/pull/6860 and https://github.com/apache/arrow-datafusion/pull/6835 conflicted logically and cause compilation to fail on `main`:

https://github.com/apache/arrow-datafusion/actions/runs/5483558927/jobs/9990031096

```
Compiling datafusion v27.0.0 (D:\a\arrow-datafusion\arrow-datafusion\datafusion\core)
error[E0252]: the name `DisplayFormatType` is defined multiple times
  --> datafusion\core\src\physical_plan\streaming.rs:38:24
   |
34 |     DisplayFormatType, ExecutionPlan, Partitioning, SendableRecordBatchStream,
   |     ----------------- previous import of the type `DisplayFormatType` here
...
38 | use super::{DisplayAs, DisplayFormatType};
   |                        ^^^^^^^^^^^^^^^^^ `DisplayFormatType` reimported here
   |
   = note: `DisplayFormatType` must be defined only once in the type namespace of this module

error[E0407]: method `fmt_as` is not a member of trait `ExecutionPlan`
   --> datafusion\core\src\physical_plan\streaming.rs:167:5
    |
167 | /     fn fmt_as(
168 | |         &self,
169 | |         t: DisplayFormatType,
170 | |         f: &mut std::fmt::Formatter,
...   |
203 | |         }
204 | |     }
    | |_____^ not a member of trait `ExecutionPlan`

warning: unused import: `DisplayFormatType`
  --> datafusion\core\src\physical_plan\streaming.rs:38:24
   |
38 | use super::{DisplayAs, DisplayFormatType};
   |                        ^^^^^^^^^^^^^^^^^
   |
   = note: `#[warn(unused_imports)]` on by default
```

# What changes are included in this PR?
Fix conflict

# Are these changes tested?
yes, by CI

# Are there any user-facing changes?

### CODE REVIEW

**Comment by alamb** [comment]
I am going to merge this in prior to review to get main building again. I am happy to make changes as a follow on PR
