### PR TITLE
Fix: Fix build due to logical conflict

### PR DESCRIPTION
**Pull request by alamb**
# Which issue does this PR close?

None

# Rationale for this change

There is a logical conflict in https://github.com/apache/arrow-datafusion/pull/4192 and https://github.com/apache/arrow-datafusion/pull/4212 (both from @jackwener  it turns out 😆 )

Without this fix master branch is broken: https://github.com/apache/arrow-datafusion/actions/runs/3483339533/jobs/5826711615
```
error[E0609]: no field `alias` on type `&datafusion_expr::Union`
   --> datafusion/optimizer/src/propagate_empty_relation.rs:123:35
    |
123 | ...                   union.alias.clone(),
    |                             ^^^^^ unknown field
    |
    = note: available fields are: `inputs`, `schema`

error[E0560]: struct `datafusion_expr::Union` has no field named `alias`
   --> datafusion/optimizer/src/propagate_empty_relation.rs:130:25
    |
130 |                         alias: union.alias.clone(),
    |                         ^^^^^ `datafusion_expr::Union` does not have this field
    |
    = note: available fields are: `inputs`, `schema`

error[E0609]: no field `alias` on type `&datafusion_expr::Union`
   --> datafusion/optimizer/src/propagate_empty_relation.rs:130:38
    |
130 |                         alias: union.alias.clone(),
    |                                      ^^^^^ unknown field
    |
    = note: available fields are: `inputs`, `schema`
```

# What changes are included in this PR?

remove unused union alias

# Are these changes tested?
Yes existing tests

# Are there any user-facing changes?

### CODE REVIEW

**Comment by jackwener** [comment]
looks like ut exist problem, I also find some legacy code. I can clear and fix them.

**Comment by alamb** [comment]
Superceded by https://github.com/apache/arrow-datafusion/pull/4252
