### PR TITLE
Fix compiling ballista  in standalone mode, add build to CI

### PR DESCRIPTION
**Pull request by alamb**
# Which issue does this PR close?

TBD

 # Rationale for this change

As pointed by @thinkharderdev on https://github.com/apache/arrow-datafusion/pull/1810 https://github.com/apache/arrow-datafusion/pull/1810#discussion_r807259524 compiling with ballista is currently broken (likely by https://github.com/apache/arrow-datafusion/pull/1677 and https://github.com/apache/arrow-datafusion/pull/1715):

```rust
(arrow_dev) alamb@MacBook-Pro-2:~/Software/arrow-datafusion/ballista/rust$ cargo test --no-default-features --features standalone
   Compiling etcd-client v0.8.3
   Compiling ballista-scheduler v0.6.0 (/Users/alamb/Software/arrow-datafusion/ballista/rust/scheduler)
   Compiling ballista v0.6.0 (/Users/alamb/Software/arrow-datafusion/ballista/rust/client)
error[E0061]: this function takes 3 arguments but 2 arguments were supplied
  --> ballista/rust/client/src/context.rs:93:9
   |
93 |         ballista_executor::new_standalone_executor(scheduler, concurrent_tasks).await?;
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ ---------  ---------------- supplied 2 arguments
   |         |
   |         expected 3 arguments
   |
note: function defined here
  --> /Users/alamb/Software/arrow-datafusion/ballista/rust/executor/src/standalone.rs:38:14
   |
38 | pub async fn new_standalone_executor<
   |              ^^^^^^^^^^^^^^^^^^^^^^^

For more information about this error, try `rustc --explain E0061`.
error: could not compile `ballista` due to previous error
warning: build failed, waiting for other jobs to finish...
error: build failed
```

# What changes are included in this PR?
1. Fix compile
2. Add `cargo test --features=standalone` for ballista to CI
3. Disabled `test_task_stuck_when_referenced_task_failed` test due to https://github.com/apache/arrow-datafusion/issues/1840

# Are there any user-facing changes?
No

### CODE REVIEW

File: ballista/rust/client/src/context.rs [hunk 1]
```diff
@@ -458,13 +469,16 @@ mod tests {
 
     #[tokio::test]
     #[cfg(feature = "standalone")]
+    #[ignore]
```
Comment (alamb) [inline ballista/rust/client/src/context.rs:472]: This test is failing 🦜 😢 : https://github.com/apache/arrow-datafusion/issues/1840

Comment (thinkharderdev) [reply ballista/rust/client/src/context.rs:472]: yeah, that's where I got stuck as well :). I can take a look at the failing test and fix it another PR. Thanks!
