### PR TITLE
suppport bitwise and as an example

### PR DESCRIPTION
**Pull request by liukun4515**
# Which issue does this PR close?

part of https://github.com/apache/arrow-datafusion/issues/1619

 # Rationale for this change

# What changes are included in this PR?

# Are there any user-facing changes?

### CODE REVIEW

File: datafusion/src/physical_plan/expressions/binary.rs [hunk 1]
```diff
@@ -334,6 +334,141 @@ fn modulus_decimal(left: &DecimalArray, right: &DecimalArray) -> Result<DecimalA
     Ok(decimal_builder.finish())
 }
 
+fn bitwise_and(left: ArrayRef, right: ArrayRef) -> Result<ArrayRef> {
```
Comment (alamb) [inline datafusion/src/physical_plan/expressions/binary.rs:337]: yeah, these kernels would really be nicer if they were in arrow (where we can probably leverage all the bitwise hackery). It is reasonable to start in datafusion however, and then move them to arrow

Comment (liukun4515) [reply datafusion/src/physical_plan/expressions/binary.rs:337]: > yeah, these kernels would really be nicer if they were in arrow (where we can probably leverage all the bitwise hackery). It is reasonable to start in datafusion however, and then move them to arrow

agree with you.
We can implement them in datafusion now, and migrate them to arrow kernel later.
But the intention of this pr is as an example for adding bitwise operation, I wish more contributors can be involved in datafusion and make the contribution from a `new contributor friendly issue`.

**Comment by liukun4515** [comment]
@alamb @houqp @FauxFaux  PTAL

File: datafusion/src/physical_plan/expressions/binary.rs [hunk 2]
```diff
@@ -334,6 +334,100 @@ fn modulus_decimal(left: &DecimalArray, right: &DecimalArray) -> Result<DecimalA
...
+            Ok(new_null_array(array.data_type(), len))
+        } else {
+            let right: $TYPE = scalar.try_into().unwrap();
+            let result = (0..len)
+                .into_iter()
+                .map(|i| {
+                    if array.is_null(i) {
+                        None
+                    } else {
+                        Some(array.value(i) & right)
```
Comment (alamb) [inline datafusion/src/physical_plan/expressions/binary.rs:377]: Is this supposed to be `$OP` rather than `&`?

```suggestion
                        Some(array.value(i) $OP right)
```

I don't think it matters for correctness but it may be confusing in the future

File: datafusion/src/physical_plan/expressions/binary.rs [hunk 3]
```diff
@@ -334,6 +334,100 @@ fn modulus_decimal(left: &DecimalArray, right: &DecimalArray) -> Result<DecimalA
...
+        let len = $LEFT.len();
+        let left = $LEFT.as_any().downcast_ref::<$ARRAY_TYPE>().unwrap();
+        let right = $RIGHT.as_any().downcast_ref::<$ARRAY_TYPE>().unwrap();
+        let result = (0..len)
+            .into_iter()
+            .map(|i| {
+                if left.is_null(i) || right.is_null(i) {
+                    None
+                } else {
+                    Some(left.value(i) & right.value(i))
```
Comment (alamb) [inline datafusion/src/physical_plan/expressions/binary.rs:351]: As below, I think this is meant to be `$OP`

```suggestion
                    Some(left.value(i) $OP right.value(i))
```

**Review by alamb — DISMISSED** [review]

**Comment by alamb** [comment]
When I merged this branch from master I also found it had a compiler error due to some sort of logical conflicts:

```shell
   Compiling datafusion v6.0.0 (/Users/alamb/Software/arrow-datafusion/datafusion)
error[E0308]: mismatched types
    --> datafusion/src/physical_plan/expressions/binary.rs:1154:56
     |
1154 |             Operator::BitwiseAnd => bitwise_and_scalar(array, scalar.clone()),
     |                                                        ^^^^^ expected struct `Arc`, found trait object `dyn arrow::array::Array`
     |
     = note: expected reference `&Arc<(dyn arrow::array::Array + 'static)>`
                found reference `&dyn arrow::array::Array`


```


And I had to apply this to fix:

```diff
diff --git a/datafusion/src/physical_plan/expressions/binary.rs b/datafusion/src/physical_plan/expressions/binary.rs
index 82dacf760..d00106fb8 100644
--- a/datafusion/src/physical_plan/expressions/binary.rs
+++ b/datafusion/src/physical_plan/expressions/binary.rs
@@ -419,7 +419,7 @@ fn bitwise_and(left: ArrayRef, right: ArrayRef) -> Result<ArrayRef> {
     }
 }
 
-fn bitwise_and_scalar(array: &ArrayRef, scalar: ScalarValue) -> Option<Result<ArrayRef>> {
+fn bitwise_and_scalar(array: &dyn Array, scalar: ScalarValue) -> Option<Result<ArrayRef>> {
     let result = match array.data_type() {
         DataType::Int8 => {
             binary_bitwise_array_scalar!(array, scalar, &, Int8Array, i8)

```

**Comment by alamb** [comment]
@liukun4515  I hope you don't mind but I took the liberty of merging your branch with `master` and fixing the logical conflict

File: datafusion/src/physical_plan/expressions/binary.rs (hunk 3 above)
Comment (alamb) [reply datafusion/src/physical_plan/expressions/binary.rs]: Changed in https://github.com/apache/arrow-datafusion/pull/1653/commits/f81bffb326609be62e7468073ddc69f22171b69f (I was trying to make a follow on PR but then I found the logical conflict so I figured I would fix it directly on this PR). 

I hope that is OK with you

**Review by alamb — APPROVED** [review]

File: datafusion/src/physical_plan/expressions/binary.rs (hunk 3 above)
Comment (liukun4515) [reply datafusion/src/physical_plan/expressions/binary.rs]: This is from my mistake.

**Comment by liukun4515** [comment]
It does not matter. @alamb 
It's spring festival in china, I can't respond in time recently.
Thanks for your careful review.

**Comment by alamb** [comment]
> It's spring festival in china, I can't respond in time recently.

No worries at all.
