### ISSUE TITLE
Error in `python test` check / maturn python build:  `function or associated item not found in `proc_macro::Literal`

### ISSUE THREAD

**Issue by alamb** [apache/arrow-datafusion#961]
**Describe the bug**
The  `python test` CI test started failing

https://github.com/apache/arrow-datafusion/runs/3472141634

```
   Compiling alloc-stdlib v0.2.1
   Compiling lock_api v0.4.5
error[E0599]: no function or associated item named `from_str` found for struct `proc_macro::Literal` in the current scope
   --> /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/proc-macro2-1.0.29/src/wrapper.rs:926:38
    |
926 |                 proc_macro::Literal::from_str(repr)
    |                                      ^^^^^^^^ function or associated item not found in `proc_macro::Literal`


error: aborting due to previous error


For more information about this error, try `rustc --explain E0599`.

error: could not compile `proc-macro2`

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: build failed
💥 maturin failed
  Caused by: Failed to build a native library through cargo
  Caused by: Failed to build a native library through cargo
  Caused by: Cargo build finished with "exit status: 101": `cargo rustc --message-format json --manifest-path Cargo.toml --lib --`
Error: Process completed with exit code 1.

```
**To Reproduce**

**Expected behavior**

**Additional context**

**Comment by charliec443** [comment]
Rolling pyo3 to `pyo3 = { version = "=0.14.3", features = ["extension-module"] }` seems to do the trick...not that its an appropriate fix

**Comment by houqp** [comment]
I haven't had the time to dig into this yet, but here is the diff in 0.14.4 release: https://github.com/PyO3/pyo3/compare/v0.14.3...v0.14.4

**Comment by houqp** [comment]
This is caused by https://github.com/dtolnay/proc-macro2/pull/296, pinning `proc-macro2` to 1.0.28 fixes the build issue for rust >= 1.54.
